#!/bin/bash
python3 -c "
w='water';s='stir';b='bestchol'
W=sum(w.index(c)*5**i for i,c in enumerate(reversed('$WATER')))
S=sum(s.index(c)*4**i for i,c in enumerate(reversed('$STIR'.split('.')[0])))
n=W+S
r=''
while n:r=b[n%8]+r;n//=8
print(r)
"
