#!/bin/bash
python3 -c "print(\"\".join(\"bestchol\"[int(d)] for d in oct(sum(\"water\".index(c)*5**i for i,c in enumerate(\"$WATER\"[::-1]))+sum(\"stir\".index(c)*4**i for i,c in enumerate(\"$STIR\".split(\".\")[0][::-1])))[2:]))"
