#!/usr/bin/env bash
# Script that indefinitely writes "I am alive!" to /tmp/my_process with a 2-second pause between iterations
while true
do
    echo "I am alive!" >> /tmp/my_process
    sleep 2
done
